import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const isDev = process.env.NODE_ENV !== "production";

  // ⚠️ SOMENTE EM DEV (evita apagar o banco em produção no Railway)
  if (isDev) {
    await prisma.poi.deleteMany();
  }

  await prisma.poi.createMany({
    data: [
      // =================================================================
      // MACEIÓ (CAPITAL) - PRAIAS E PONTOS URBANOS
      // =================================================================
      {
        name: "Pavilhão do Artesanato",
        description: "Feira de artesanato tradicional na Pajuçara, ícone da cultura local.",
        category: "Compras/Cultura",
        address: "Av. Dr. Antônio Gouveia, Pajuçara, Maceió - AL",
        lat: -9.664167,
        lng: -35.712778,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Piscinas Naturais de Pajuçara",
        description: "Formações de recifes acessíveis por jangada, cartão-postal da capital.",
        category: "Natureza",
        address: "Praia de Pajuçara, Maceió - AL",
        lat: -9.6738,
        lng: -35.7036,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Marco dos Corais (Antigo Alagoinhas)",
        description: "Mirante e passarela sobre o mar na Ponta Verde.",
        category: "Natureza/Lazer",
        address: "Praça Gogó da Ema, Ponta Verde, Maceió - AL",
        lat: -9.6619,
        lng: -35.7018,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Catedral Metropolitana de Maceió",
        description: "Principal templo católico da cidade, no Centro Histórico.",
        category: "História",
        address: "Praça Dom Pedro II, Centro, Maceió - AL",
        lat: -9.665278,
        lng: -35.735556,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mirante de São Gonçalo",
        description: "Oferece uma vista panorâmica do porto e do centro histórico.",
        category: "História/Mirante",
        address: "Farol, Maceió - AL",
        lat: -9.6608,
        lng: -35.7389,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Bairro Histórico de Jaraguá",
        description: "Região histórica com armazéns e arquitetura antiga preservada.",
        category: "História",
        address: "Jaraguá, Maceió - AL",
        lat: -9.6725,
        lng: -35.7222,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // LITORAL NORTE (COSTA DOS CORAIS)
      // =================================================================
      {
        name: "Galés de Maragogi",
        description: "Famosas piscinas naturais do Caribe Brasileiro.",
        category: "Natureza",
        address: "Maragogi - AL",
        lat: -9.0275,
        lng: -35.2045,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia de Antunes",
        description: "Praia paradisíaca conhecida por suas águas azuis turquesa.",
        category: "Natureza",
        address: "Maragogi - AL",
        lat: -8.9866,
        lng: -35.1958,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia do Patacho",
        description: "Praia tranquila e preservada, única em Alagoas com Bandeira Azul.",
        category: "Natureza",
        address: "Porto de Pedras - AL",
        lat: -9.2155,
        lng: -35.2974,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Capela dos Milagres",
        description: "Famosa capela à beira-mar, ícone da Rota Ecológica.",
        category: "Cultura",
        address: "São Miguel dos Milagres - AL",
        lat: -9.2687,
        lng: -35.3582,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Associação Peixe-Boi",
        description: "Santuário de preservação e observação do peixe-boi marinho.",
        category: "Natureza/Ecológico",
        address: "Tatuamunha, Porto de Pedras - AL",
        lat: -9.2312,
        lng: -35.3341,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mirante do Aruanã",
        description: "Vista panorâmica das praias de Japaratinga.",
        category: "Natureza",
        address: "Japaratinga - AL",
        lat: -9.0983,
        lng: -35.2572,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // LITORAL SUL
      // =================================================================
      {
        name: "Praia do Francês",
        description: "Uma das praias mais populares do estado, com barreira de corais.",
        category: "Natureza",
        address: "Marechal Deodoro - AL",
        lat: -9.7719,
        lng: -35.8398,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia da Barra de São Miguel",
        description: "Águas calmas protegidas por recifes, ideal para banho.",
        category: "Natureza",
        address: "Barra de São Miguel - AL",
        lat: -9.8405,
        lng: -35.9038,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mirante do Gunga",
        description: "Vista espetacular do vasto coqueiral da Praia do Gunga.",
        category: "Natureza",
        address: "Roteiro - AL",
        lat: -9.8569,
        lng: -35.9080,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Falésias do Gunga",
        description: "Formações geológicas coloridas acessíveis por buggy.",
        category: "Aventura",
        address: "Roteiro - AL",
        lat: -9.8800,
        lng: -35.9200,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Pontal do Peba",
        description: "Praia extensa e área de proteção ambiental, encontro com dunas.",
        category: "Natureza",
        address: "Piaçabuçu - AL",
        lat: -10.3333,
        lng: -36.2833,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Foz do Rio São Francisco",
        description: "O encontro majestoso do Velho Chico com o mar.",
        category: "Natureza",
        address: "Piaçabuçu - AL",
        lat: -10.5058,
        lng: -36.3986,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // CIDADES HISTÓRICAS E CULTURA (AGRESTE/ZONA DA MATA)
      // =================================================================
      {
        name: "Centro Histórico de Marechal Deodoro",
        description: "Cidade natal do primeiro presidente, arquitetura colonial preservada.",
        category: "História",
        address: "Marechal Deodoro - AL",
        lat: -9.7110,
        lng: -35.8965,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Parque Memorial Quilombo dos Palmares",
        description: "Solo sagrado da resistência negra e palco de Zumbi dos Palmares.",
        category: "História/Cultura",
        address: "Serra da Barriga, União dos Palmares - AL",
        lat: -9.1764,
        lng: -36.0911,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Centro Histórico de Penedo",
        description: "Patrimônio histórico com igrejas barrocas às margens do Rio São Francisco.",
        category: "História",
        address: "Penedo - AL",
        lat: -10.2905,
        lng: -36.5866,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Igreja Nossa Senhora da Corrente",
        description: "Igreja histórica em Penedo com detalhes em ouro e azulejos portugueses.",
        category: "História",
        address: "Penedo - AL",
        lat: -10.2898,
        lng: -36.5872,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // SERTÃO E CÂNIONS
      // =================================================================
      {
        name: "Centro Histórico de Piranhas",
        description: "Cidade 'Lapinha do Sertão', arquitetura colorida e história do Cangaço.",
        category: "História",
        address: "Piranhas - AL",
        lat: -9.6247,
        lng: -37.7561,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mirante Secular",
        description: "Ponto alto com vista para o Rio São Francisco e a cidade de Piranhas.",
        category: "Mirante",
        address: "Piranhas - AL",
        lat: -9.6225,
        lng: -37.7580,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Cânions do Xingó (Porto de Embarque)",
        description: "Ponto de partida para os majestosos cânions navegáveis do São Francisco.",
        category: "Natureza",
        address: "Piranhas/Delmiro Gouveia - AL",
        lat: -9.6455,
        lng: -37.7944,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Museu do Sertão",
        description: "Acervo sobre a cultura sertaneja e a história do cangaço.",
        category: "História",
        address: "Piranhas - AL",
        lat: -9.6253,
        lng: -37.7558,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Rota do Cangaço (Grota de Angico)",
        description: "Trilha histórica que leva ao local da morte de Lampião.",
        category: "História/Aventura",
        address: "Poço Redondo (Acesso via Piranhas) - AL/SE",
        lat: -9.6580,
        lng: -37.6900,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // MACEIÓ (ZONA NORTE, LAGOAS E ARTESANATO)
      // =================================================================
      {
        name: "Bairro das Rendeiras (Pontal da Barra)",
        description: "Famoso núcleo de artesanato do bordado Filé e pôr do sol na Lagoa Mundaú.",
        category: "Cultura/Compras",
        address: "Pontal da Barra, Maceió - AL",
        lat: -9.6953,
        lng: -35.7644,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Parque Municipal de Maceió",
        description: "Reserva de Mata Atlântica dentro da cidade, com trilhas, fontes e jacarés.",
        category: "Natureza",
        address: "Bebedouro, Maceió - AL",
        lat: -9.6108,
        lng: -35.7633,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia de Ipioca",
        description: "Praia tranquila no litoral norte de Maceió, famosa pelos beach clubs e águas calmas.",
        category: "Natureza/Lazer",
        address: "Ipioca, Maceió - AL",
        lat: -9.5167,
        lng: -35.5833,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia de Guaxuma",
        description: "Praia popular entre os locais, com quiosques rústicos e clima familiar.",
        category: "Natureza",
        address: "Guaxuma, Maceió - AL",
        lat: -9.5833,
        lng: -35.6667,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // LITORAL NORTE (NOVOS PONTOS)
      // =================================================================
      {
        name: "Praia de Carro Quebrado",
        description: "Cenário selvagem com falésias coloridas e mar esverdeado. Acesso difícil garante preservação.",
        category: "Aventura/Natureza",
        address: "Barra de Santo Antônio - AL",
        lat: -9.3934,
        lng: -35.4678,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Ilha da Crôa",
        description: "Bancos de areia e águas tranquilas na foz do rio, ótimo para gastronomia local.",
        category: "Natureza",
        address: "Barra de Santo Antônio - AL",
        lat: -9.4080,
        lng: -35.5050,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Piscinas Naturais de Paripueira",
        description: "Área de proteção ambiental com piscinas naturais ricas em biodiversidade.",
        category: "Natureza",
        address: "Paripueira - AL",
        lat: -9.4800,
        lng: -35.5500,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Caminho de Moisés",
        description: "Fenômeno natural onde um banco de areia divide o mar quilômetros adentro na maré baixa.",
        category: "Natureza",
        address: "Barra Grande, Maragogi - AL",
        lat: -8.9950,
        lng: -35.2080,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia do Toque",
        description: "Uma das praias mais exclusivas de São Miguel, famosa pelas pousadas de charme.",
        category: "Natureza/Luxo",
        address: "São Miguel dos Milagres - AL",
        lat: -9.2550,
        lng: -35.3480,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // LITORAL SUL (NOVOS PONTOS)
      // =================================================================
      {
        name: "Complexo Dunas de Marapé",
        description: "Encontro do rio Jequiá com o mar, cercado por manguezais e dunas. Um clássico.",
        category: "Natureza/Lazer",
        address: "Jequiá da Praia - AL",
        lat: -10.0569,
        lng: -36.0234,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Farol do Pontal de Coruripe",
        description: "Farol histórico cercado por recifes que formam piscinas na maré baixa.",
        category: "História/Natureza",
        address: "Coruripe - AL",
        lat: -10.1750,
        lng: -36.1760,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia do Miaí de Baixo/Cima",
        description: "Praias extensas e desertas, ideais para quem busca isolamento e natureza bruta.",
        category: "Natureza",
        address: "Coruripe - AL",
        lat: -10.2100,
        lng: -36.2300,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Lagoa do Roteiro",
        description: "Lagoa que banha a Praia do Gunga, famosa pelos passeios de barco e criatórios de ostras.",
        category: "Natureza",
        address: "Roteiro - AL",
        lat: -9.8333,
        lng: -35.9167,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // SERTÃO E RIO SÃO FRANCISCO (TESOUROS ESCONDIDOS)
      // =================================================================
      {
        name: "Ilha do Ferro",
        description: "Povoado ribeirinho famoso nacionalmente pelo artesanato em madeira e bancos de areia no rio.",
        category: "Cultura/Arte",
        address: "Pão de Açúcar - AL",
        lat: -9.7456,
        lng: -37.6631,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Cristo Redentor de Pão de Açúcar",
        description: "Estátua no alto da serra com uma das vistas mais bonitas do Rio São Francisco.",
        category: "Mirante",
        address: "Pão de Açúcar - AL",
        lat: -9.7500,
        lng: -37.4333,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Usina Hidrelétrica de Angiquinho",
        description: "Primeira hidrelétrica do Nordeste, construída por Delmiro Gouveia encravada na rocha.",
        category: "História/Engenharia",
        address: "Delmiro Gouveia - AL",
        lat: -9.6598,
        lng: -37.8032,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Santuário de Santa Terezinha",
        description: "Um dos maiores santuários religiosos de Alagoas, em região serrana.",
        category: "Religião",
        address: "Mata Grande - AL",
        lat: -9.1167,
        lng: -37.7333,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // AGRESTE, SERRAS E CACHOEIRAS
      // =================================================================
      {
        name: "Cachoeira da Tiririca",
        description: "Queda d'água dentro de uma reserva de Mata Atlântica, ideal para ecoturismo.",
        category: "Natureza/Aventura",
        address: "Murici - AL",
        lat: -9.2333,
        lng: -35.9500,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mar Vermelho (Suíça Alagoana)",
        description: "Cidade serrana conhecida pelo clima frio, neblina e festivais de inverno.",
        category: "Clima/Lazer",
        address: "Mar Vermelho - AL",
        lat: -9.4475,
        lng: -36.3886,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Santuário Ecológico da Fazenda Santa Tereza",
        description: "Reserva particular com trilhas e piscinas naturais de água doce.",
        category: "Natureza",
        address: "Atalaia - AL",
        lat: -9.5000,
        lng: -36.0167,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Casa de Graciliano Ramos",
        description: "Museu casa onde viveu o autor de Vidas Secas, preservando sua memória.",
        category: "História/Literatura",
        address: "Palmeira dos Índios - AL",
        lat: -9.4058,
        lng: -36.6325,
        imageUrl: null,
        arUrl: null,
      },
      // =================================================================
      // MACEIÓ E REGIÃO METROPOLITANA (LAGOAS E HISTÓRIA)
      // =================================================================
      {
        name: "Mirante de Santa Amélia",
        description: "Vista panorâmica espetacular da Lagoa Mundaú, ideal para o pôr do sol.",
        category: "Mirante/Natureza",
        address: "Santa Amélia, Maceió - AL",
        lat: -9.5985,
        lng: -35.7722,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Igreja de Nossa Senhora Mãe dos Homens",
        description: "Joia do barroco alagoano com azulejos portugueses raros, à beira da lagoa.",
        category: "História/Arquitetura",
        address: "Coqueiro Seco - AL",
        lat: -9.6386,
        lng: -35.8025,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia de Tabuba",
        description: "Encontro do rio com o mar, águas mornas e falésias vivas. Vizinha a Carro Quebrado.",
        category: "Natureza",
        address: "Barra de Santo Antônio - AL",
        lat: -9.4320,
        lng: -35.5340,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // AGRESTE E ZONA DA MATA (AVENTURA E CACHOEIRAS)
      // =================================================================
      {
        name: "Cachoeira do Anel",
        description: "A cachoeira mais famosa do estado, cenário cinematográfico em propriedade rural.",
        category: "Aventura/Natureza",
        address: "Viçosa - AL",
        lat: -9.3872,
        lng: -36.1833,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Planetário e Casa da Ciência",
        description: "Um dos maiores planetários digitais do Brasil, localizado no Lago da Perucaba.",
        category: "Ciência/Cultura",
        address: "Lago da Perucaba, Arapiraca - AL",
        lat: -9.7634,
        lng: -36.6622,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Cachoeira do Gusmão",
        description: "Queda d'água com temperatura fria, em região de mata serrana.",
        category: "Natureza",
        address: "Ibateguara - AL",
        lat: -8.9667,
        lng: -35.9333,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Serra da Chã Preta",
        description: "Destino de turismo rural e clima ameno, com trilhas e mirantes.",
        category: "Natureza/Rural",
        address: "Chã Preta - AL",
        lat: -9.2558,
        lng: -36.2944,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // LITORAL NORTE (DETALHES ESPECÍFICOS)
      // =================================================================
      {
        name: "Bica do Boqueirão",
        description: "Fontes de água natural em Japaratinga, usadas para banho há séculos.",
        category: "Natureza/História",
        address: "Japaratinga - AL",
        lat: -9.0910,
        lng: -35.2630,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia do Marceneiro",
        description: "Praia famosa pela capela à beira-mar (Capela dos Milagres fica próxima) e mar calmo.",
        category: "Natureza",
        address: "Passo de Camaragibe - AL",
        lat: -9.2880,
        lng: -35.3660,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mosteiro de São Bento",
        description: "Localizado no alto de um morro em Maragogi, com vista para o mar e biscoitos artesanais.",
        category: "Religião/História",
        address: "Maragogi (Povoado de São Bento) - AL",
        lat: -9.0667,
        lng: -35.2333,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // SERTÃO E ALTO SERTÃO (HISTÓRIA E FRONTEIRAS)
      // =================================================================
      {
        name: "Ponte Metálica Dom Pedro II",
        description: "Marco da engenharia que liga Alagoas à Bahia sobre o cânion do Rio São Francisco.",
        category: "História/Engenharia",
        address: "Delmiro Gouveia - AL",
        lat: -9.4883,
        lng: -38.0167,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Trilha do Talhado",
        description: "Trilha ecológica entre paredões de pedra no bioma da Caatinga.",
        category: "Aventura",
        address: "Olho d'Água do Casado - AL",
        lat: -9.5167,
        lng: -37.8333,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Centro Histórico de Água Branca",
        description: "Casarões coloniais preservados em uma das cidades mais altas e frias do estado.",
        category: "História",
        address: "Água Branca - AL",
        lat: -9.2611,
        lng: -37.9389,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Museu Regional de Delmiro Gouveia",
        description: "Conta a história da industrialização do sertão e da Fábrica da Pedra.",
        category: "História",
        address: "Delmiro Gouveia - AL",
        lat: -9.3890,
        lng: -37.9980,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // LITORAL SUL (ESCAPES TRANQUILOS)
      // =================================================================
      {
        name: "Praia de Feliz Deserto",
        description: "Como o nome diz, uma praia isolada, com coqueirais e artesanato de palha de ouricuri.",
        category: "Natureza/Cultura",
        address: "Feliz Deserto - AL",
        lat: -10.2833,
        lng: -36.3000,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Lagoa do Pau",
        description: "Praia com ondas mais fortes e cenário rústico, frequentada por surfistas.",
        category: "Natureza/Surf",
        address: "Coruripe - AL",
        lat: -10.1333,
        lng: -36.1333,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia do Peba (Vila de Pescadores)",
        description: "Área da vila, famosa pela gastronomia de camarão e grandes faixas de areia.",
        category: "Gastronomia/Natureza",
        address: "Piaçabuçu - AL",
        lat: -10.3500,
        lng: -36.2667,
        imageUrl: null,
        arUrl: null,
      },
      // =================================================================
      // MACEIÓ E ENTORNO (HISTÓRIA INDUSTRIAL E GASTRONOMIA)
      // =================================================================
      {
        name: "Bairro de Fernão Velho",
        description: "Antiga vila operária com estação de trem histórica e clima de cidade do interior.",
        category: "História/Cultura",
        address: "Fernão Velho, Maceió - AL",
        lat: -9.5894,
        lng: -35.8142,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia de Riacho Doce",
        description: "Famosa pelas boleiras tradicionais, igreja antiga e mar com ondas moderadas.",
        category: "Gastronomia/Praia",
        address: "Riacho Doce, Maceió - AL",
        lat: -9.5694,
        lng: -35.6322,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Ilha de Santa Rita",
        description: "Maior ilha lacustre do país, polo gastronômico da massunim e porta de entrada de Marechal.",
        category: "Gastronomia/Natureza",
        address: "Marechal Deodoro - AL",
        lat: -9.6983,
        lng: -35.8111,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // AGRESTE E ZONA DA MATA (BIODIVERSIDADE PURA)
      // =================================================================
      {
        name: "Reserva Biológica de Pedra Talhada",
        description: "Um dos mais importantes refúgios de Mata Atlântica do Nordeste, lar de aves raras.",
        category: "Ecoturismo/Ciência",
        address: "Quebrangulo - AL",
        lat: -9.3167,
        lng: -36.4667,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Cristo do Goiti",
        description: "Estátua e mirante no alto da serra, principal cartão postal de Palmeira dos Índios.",
        category: "Mirante/História",
        address: "Palmeira dos Índios - AL",
        lat: -9.4125,
        lng: -36.6340,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Estação Ferroviária de Great Western",
        description: "Patrimônio histórico arquitetônico que remonta à era de ouro do transporte ferroviário.",
        category: "História",
        address: "Rio Largo - AL",
        lat: -9.4783,
        lng: -35.8417,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // LITORAL NORTE (PRAIAS SELVAGENS E EXCLUSIVAS)
      // =================================================================
      {
        name: "Praia do Morro",
        description: "Praia deserta com falésias e mar agitado, acessível apenas por trilha ou barco.",
        category: "Aventura/Natureza",
        address: "Passo de Camaragibe - AL",
        lat: -9.3333,
        lng: -35.3917,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia de Lages",
        description: "Vizinha exclusiva da Praia do Patacho, com coqueirais densos e quase nenhuma construção.",
        category: "Natureza/Luxo",
        address: "Porto de Pedras - AL",
        lat: -9.1910,
        lng: -35.3160,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia de Sonho Verde",
        description: "Mar calmo protegido por recifes e muita sombra de casuarinas, ideal para famílias.",
        category: "Natureza",
        address: "Paripueira - AL",
        lat: -9.5290,
        lng: -35.5610,
        imageUrl: null,
        arUrl: null,
      },

      // =================================================================
      // LITORAL SUL (LAGOAS E HISTÓRIA PROFUNDA)
      // =================================================================
      {
        name: "Lagoa Azeda",
        description: "Povoado rústico e praia tranquila, onde a lagoa encontra o mar longe do turismo de massa.",
        category: "Natureza/Rural",
        address: "Jequiá da Praia - AL",
        lat: -10.0050,
        lng: -36.0020,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Convento de Santa Maria Madalena",
        description: "Parte do complexo histórico de Marechal, é uma joia da arquitetura sacra.",
        category: "História/Religião",
        address: "Marechal Deodoro - AL",
        lat: -9.7095,
        lng: -35.8955,
        imageUrl: null,
        arUrl: null,
      },
      // ⚠️ ITEM "Lagoa do Pau" REMOVIDO AQUI PORQUE JÁ CONSTAVA ACIMA

      // =================================================================
      // BAIXO SÃO FRANCISCO E SERTÃO (DUNAS E MÚSICA)
      // =================================================================
      {
        name: "Traipu (Cidade dos Músicos)",
        description: "Cidade histórica à beira do Velho Chico, conhecida pelas dunas de água doce e tradição musical.",
        category: "Cultura/Natureza",
        address: "Traipu - AL",
        lat: -9.9628,
        lng: -37.0033,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Dunas do Cavalo Russo",
        description: "Formações de areia dourada às margens do Rio São Francisco, perfeitas para banho.",
        category: "Natureza",
        address: "Traipu - AL",
        lat: -9.9500,
        lng: -37.0200,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Povoado de Piau",
        description: "Localidade famosa pelo artesanato tradicional de 'Boa Noite' (tipo de bordado).",
        category: "Cultura/Artesanato",
        address: "Piranhas - AL",
        lat: -9.5800,
        lng: -37.7100,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mirante da Santa de Belo Monte",
        description: "Vista privilegiada de uma das curvas mais bonitas do Rio São Francisco.",
        category: "Mirante",
        address: "Belo Monte - AL",
        lat: -9.8250,
        lng: -37.2780,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Polo Gastronômico da Massagueira",
        description: "Maior polo gastronômico a céu aberto do Nordeste, famoso pelos frutos do mar e doces caseiros.",
        category: "Gastronomia",
        address: "Massagueira, Marechal Deodoro - AL",
        lat: -9.7228,
        lng: -35.8080,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Ilha de Carlito",
        description: "Ilha na Lagoa Mundaú com estrutura de lazer e piscina no meio da lagoa.",
        category: "Lazer/Natureza",
        address: "Marechal Deodoro (Acesso via barco) - AL",
        lat: -9.6833,
        lng: -35.7833,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Barra Nova",
        description: "Prainha de águas calmas no encontro da lagoa com o mar, com piscinas naturais na maré baixa.",
        category: "Natureza/Praia",
        address: "Marechal Deodoro - AL",
        lat: -9.7397,
        lng: -35.8192,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Museu de Paleontologia de Maravilha",
        description: "Abriga fósseis de preguiças gigantes e tigres-dente-de-sabre encontrados na região.",
        category: "Ciência/História",
        address: "Maravilha - AL",
        lat: -9.2333,
        lng: -37.3500,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Serra da Agulha",
        description: "Formação rochosa imponente, ideal para trilhas e rapel no sertão.",
        category: "Aventura",
        address: "Santana do Ipanema - AL",
        lat: -9.3667,
        lng: -37.2333,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Toca da Raposa",
        description: "Sítio arqueológico com pinturas rupestres preservadas.",
        category: "História/Arqueologia",
        address: "Santana do Ipanema - AL",
        lat: -9.3800,
        lng: -37.2500,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Santuário Frei Damião",
        description: "Grande santuário de peregrinação no distrito de Canafístula.",
        category: "Religião",
        address: "Canafístula, Palmeira dos Índios - AL",
        lat: -9.4500,
        lng: -36.5833,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Cruzeiro do Morro Santo",
        description: "Ponto de fé com vista panorâmica da cidade de Arapiraca.",
        category: "Religião/Mirante",
        address: "Arapiraca - AL",
        lat: -9.7500,
        lng: -36.6500,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Igreja de São Benedito (A Igrejinha)",
        description: "Cartão postal à beira-mar em Japaratinga, construída pelos holandeses (lenda local).",
        category: "História/Religião",
        address: "Japaratinga - AL",
        lat: -9.0915,
        lng: -35.2635,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Parque do Horto",
        description: "Antiga reserva do IBAMA, hoje parque aberto com trilhas e muitos animais silvestres.",
        category: "Natureza/Lazer",
        address: "Gruta de Lourdes, Maceió - AL",
        lat: -9.6200,
        lng: -35.7400,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mercado da Produção",
        description: "A alma gastronômica de Maceió. Onde se compra carne de sol, queijo coalho e artesanato de palha.",
        category: "Cultura/Gastronomia",
        address: "Levada, Maceió - AL",
        lat: -9.6550,
        lng: -35.7480,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mirante de Chã de Bebedouro",
        description: "Vista única da Lagoa Mundaú e da ponte Divaldo Suruagy.",
        category: "Mirante",
        address: "Chã de Bebedouro, Maceió - AL",
        lat: -9.6300,
        lng: -35.7600,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Comunidade Quilombola do Muquém",
        description: "Famosa pela cerâmica de barro manual, herança direta de Zumbi.",
        category: "Cultura/Artesanato",
        address: "União dos Palmares - AL",
        lat: -9.1800,
        lng: -36.1100,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Baobá Gigante de Alagoas",
        description: "Árvore centenária símbolo da resistência negra, localizada em Piaçabuçu.",
        category: "Natureza/História",
        address: "Piaçabuçu - AL",
        lat: -10.4050,
        lng: -36.4340,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Túnel Verde de Milagres",
        description: "Trecho da estrada AL-101 cercado por árvores que formam um túnel natural.",
        category: "Natureza/Fotografia",
        address: "São Miguel dos Milagres - AL",
        lat: -9.2700,
        lng: -35.3700,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Praia da Bruna",
        description: "Praia em Maragogi famosa pelas redes na água e cenário instagramável.",
        category: "Lazer",
        address: "Peroba, Maragogi - AL",
        lat: -8.9700,
        lng: -35.1800,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Fonte da Camboa",
        description: "Fonte de água doce potável que brota na areia da praia.",
        category: "Natureza",
        address: "Paripueira - AL",
        lat: -9.4700,
        lng: -35.5400,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Rio Niquim",
        description: "Rio de águas escuras e geladas que deságua na Barra de São Miguel, ótimo para banho.",
        category: "Natureza",
        address: "Barra de São Miguel - AL",
        lat: -9.8350,
        lng: -35.9000,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Reserva Extrativista Marinha da Lagoa do Jequiá",
        description: "Área de proteção ambiental com manguezais preservados e pesca artesanal.",
        category: "Natureza",
        address: "Jequiá da Praia - AL",
        lat: -10.0300,
        lng: -36.0200,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Casa de Maria Bonita",
        description: "Museu na casa onde nasceu a Rainha do Cangaço.",
        category: "História",
        address: "Malhada da Caiçara, Paulo Afonso (Divisa/Acesso AL) - AL/BA",
        lat: -9.3900,
        lng: -38.2200,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Torre do Relógio de Piranhas",
        description: "Ícone arquitetônico no centro histórico, construído em 1879.",
        category: "História",
        address: "Piranhas - AL",
        lat: -9.6250,
        lng: -37.7565,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mata da Cafurna",
        description: "Reserva florestal em Palmeira dos Índios, clima frio e trilhas.",
        category: "Natureza",
        address: "Palmeira dos Índios - AL",
        lat: -9.3800,
        lng: -36.6500,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Mirante da Serra da Barriga",
        description: "Local específico no topo da serra para observação astronômica e do vale.",
        category: "Mirante",
        address: "União dos Palmares - AL",
        lat: -9.1760,
        lng: -36.0910,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Ruínas do Antigo Engenho de Água Branca",
        description: "Vestígios históricos do ciclo do açúcar no sertão.",
        category: "História",
        address: "Água Branca - AL",
        lat: -9.2600,
        lng: -37.9350,
        imageUrl: null,
        arUrl: null,
      },
      {
        name: "Engenho Guaxuma",
        description: "Engenho histórico em Coruripe, cenário de novelas e filmes.",
        category: "História/Cultura",
        address: "Coruripe - AL",
        lat: -10.1200,
        lng: -36.1700,
        imageUrl: null,
        arUrl: null,
      },
    ],
    skipDuplicates: true,
  });

  console.log("✅ Seed completo de Alagoas concluído.");
}

main()
  .catch((e) => {
    console.error("❌ Erro no seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });